api_auth:
    path: /api/auth
    methods: ['POST']
    
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_doc:
    path: /
    controller: api_platform.swagger_ui.action

